<a href="https://colab.research.google.com/github/JuanArocaMIAR/03MIAR---Algoritmos-de-Optimizacion---2023/blob/main/Trabajo_Pr%C3%A1ctico_Algoritmos_Juan_Aroca_Perez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Trabajo Práctico<br>
Nombre y Apellidos: Juan Aroca Pérez  <br>
Url: https://github.com/JuanArocaMIAR/03MIAR---Algoritmos-de-Optimizacion---2023.git <br>
Google Colab: https://colab.research.google.com/drive/17WXjPqby0x88NQ9ba7rwcmoBw6ON4PdA#scrollTo=ZfaVmbA9ShoG <br>

Problema:
>1. Sesiones de doblaje <br>


**Descripción del problema:**

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible.







                                        

#Modelo
- ¿Como represento el espacio de soluciones?
- ¿Cual es la función objetivo?
- ¿Como implemento las restricciones?

**¿Cómo represento el espacio de soluciones?**

Cada nodo del árbol de búsqueda representa una posible asignación de actores a tomas de la película. Por ejemplo, si se tiene la solución [3, 1, 6, 2, 5, 7, 4, 9, 6, 8] quiere decir que:
El actor 0 ha sido asignado a la toma 3, el actor 1 a la toma 1, etc.


**¿Cuál es la función objetivo?**

Dado que el objetivo es minimizar el coste total de la grabación, la función objetivo se define como la suma de los costes de todas las tomas. En este caso, la función ***gasto_total*** calcula exactamente eso.

**¿Cómo implemento las restricciones?**

Las restricciones se implementan en la función ***generar_hijos_ordenados***. Esta función genera los posibles nodos hijos a partir de un nodo dado, asegurando que se respeten las restricciones del problema.

#Análisis
- ¿Que complejidad tiene el problema?. Orden de complejidad y Contabilizar el espacio de soluciones

El orden de complejidad del problema es factorial, es decir, **O(N!)**.

Por otro lado, en cuanto al espacio de soluciones, es **30^10** ya que hay 30 tomas para 10 actores, es decir, el espacio de soluciones es muy grande.

Debido al gran espacio de soluciones, es necesario el uso de algoritmos que sean eficientes en este tipo de problemas, por lo que se podría intentar solucionar mediante la **técnica de ramificación y poda**.

#Diseño
- ¿Que técnica utilizo? ¿Por qué?

En primer lugar, se pensó en utilizar ramificación y poda debido a su capacidad para manejar problemas de optimización combinatoria de manera eficiente, reduciendo la cantidad de soluciones exploradas y permitiendo encontrar la solución óptima en un tiempo razonable. Pero dado que el tiempo para encontrar una solución era excesivo se decidió incorporar componentes heurísticos como la selección de un nodo prometedor o la ordenación de los nodos hijo, reduciendo así el tiempo.

La idea de la poda es eliminar del espacio de búsqueda soluciones que sabemos que no conducirán a la solución óptima o a una solución mejor que la mejor solución actual. Esto se hace mediante la comparación de cotas superiores e inferiores en cada nodo del árbol de búsqueda.

En este caso particular, la estrategia de poda se implementa de la siguiente manera:

- En cada iteración del algoritmo, se evalúa un nodo prometedor que tiene la menor cota inferior entre todos los nodos activos.
- Se generan los hijos de este nodo prometedor.
- Para cada hijo generado, se calcula su cota inferior. Si esta cota inferior es mayor o igual que la mejor cota superior conocida entonces no tiene sentido continuar explorando este camino, ya que no conduce a una solución mejor. Por lo tanto, se poda este nodo y todos sus hijos.
- Se repite este proceso hasta que no queden nodos activos por explorar.

A continuación, se puede ver el código implementado.



#1º: Carga de los datos del problema

In [ ]:
#Respuesta
import numpy as np
import pandas as pd
from google.colab import files

# Subir el archivo CSV desde tu sistema local
archivo = files.upload()

# Seleccionar el archivo
datos = list(archivo.keys())[0]

# Cargar el dataframe desde el archivo CSV
df_actores = pd.read_csv(datos, index_col=0)

Saving Datos problema doblaje(30 tomas, 10 actores) - Hoja 1.csv to Datos problema doblaje(30 tomas, 10 actores) - Hoja 1 (1).csv


In [ ]:
matriz_tomas = df_actores.iloc[1:31, 0:10].astype(int).values
print(matriz_tomas)

[[1 1 1 1 1 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0]
 [0 1 0 0 1 0 1 0 0 0]
 [1 1 0 0 0 0 1 1 0 0]
 [0 1 0 1 0 0 0 1 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 1 0]
 [1 1 1 0 1 0 0 1 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0]
 [1 0 1 0 0 1 0 0 0 0]
 [1 1 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 1]
 [1 0 1 0 1 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]]


##2º: Ramificación y poda con componentes heurísticos:

In [ ]:
def cota_inf(nodo, matriz_tomas):
    return sum(matriz_tomas[i][nodo[i]] for i in range(len(nodo)))

def generar_hijos_ordenados(nodo, dimension, matriz_tomas):
    hijos = []
    for i in range(dimension):
        if i not in nodo:
            hijo = {'solución': nodo + (i,), 'cota inferior': cota_inf(nodo + (i,), matriz_tomas)}
            hijos.append(hijo)
    hijos.sort(key=lambda x: x['cota inferior'])
    return hijos

def gasto_total(asignacion, matriz_tomas):
    asignacion_array = np.array(asignacion)
    num_dias, num_actores = asignacion_array.shape
    gasto_total = 0
    for i in range(num_dias):
        for j in range(num_actores):
            gasto_total += matriz_tomas[asignacion_array[i][j]][i]
    return gasto_total

def ramificacion_y_poda_heuristica(matriz_tomas):
    dimension = len(matriz_tomas[0])
    mejor_solucion = tuple(i for i in range(dimension))
    cota_sup = cota_inf(mejor_solucion, matriz_tomas)

    nodos = [{'solución': (), 'cota inferior': cota_inf((), matriz_tomas)}]
    iteracion = 0

    while nodos:
        iteracion += 1
        nodo_prometedor = min(nodos, key=lambda x: x['cota inferior'])['solución']
        hijos = generar_hijos_ordenados(nodo_prometedor, dimension, matriz_tomas)

        for hijo in hijos:
            if len(hijo['solución']) == dimension:
                if hijo['cota inferior'] < cota_sup:
                    cota_sup = hijo['cota inferior']
                    mejor_solucion = hijo['solución']
            elif hijo['cota inferior'] < cota_sup:
                nodos.append(hijo)

        nodos = [x for x in nodos if x['solución'] != nodo_prometedor]

    mejor_solucion_array = np.array([list(mejor_solucion)])
    mejor_gasto = gasto_total(mejor_solucion_array, matriz_tomas)

    print("La mejor solución encontrada es:", mejor_solucion)
    print("Coste total de la mejor solución encontrada:", mejor_gasto)

ramificacion_y_poda_heuristica(matriz_tomas)


La mejor solución encontrada es: (5, 1, 0, 2, 4, 6, 7, 3, 8, 9)
Coste total de la mejor solución encontrada: 7


Se observa que aun incorporando componentes heurísticos el tiempo de ejecución sigue siendo relativamente elevado, se intenta cambiar de estrategia y utilizar otros algoritmos como el de **búsqueda local**, incorporando también componentes heurísticos como la generación de una solución inicial aleatoria.

A continuación, se puede ver el código implementado.


#3º: Búsqueda local con componentes heurísticos:

In [ ]:
# Función para calcular el gasto total de una asignación
def gasto_total(asignacion, matriz_tomas):
    num_dias, num_actores = asignacion.shape
    gasto_total = 0

    for i in range(num_dias):
        for j in range(num_actores):
            # Suma el costo de la toma asignada al actor en el día i al gasto total
            gasto_total += matriz_tomas[asignacion[i][j]][i]
    return gasto_total

# Función para generar una solución inicial aleatoria
def generar_solucion_inicial(num_dias, num_actores, num_tomas_por_dia):
    # Genera una matriz inicial de dimensiones num_dias x num_actores, inicializada con ceros
    asignacion = np.zeros((num_dias, num_actores), dtype=int)

    for i in range(num_dias):
        tomas_disponibles = np.arange(num_actores)
        np.random.shuffle(tomas_disponibles)  # Mezcla aleatoriamente los índices de los actores

        # Asigna los primeros num_tomas_por_dia actores a los primeros num_tomas_por_dia índices
        asignacion[i, :num_tomas_por_dia] = tomas_disponibles[:num_tomas_por_dia]
    return asignacion

# Intercambiar dos tomas entre días
def vecindad(asignacion):
    vecinos = []  # Inicializa una lista para almacenar los vecinos
    num_dias, num_actores = asignacion.shape

    for i in range(num_dias):
        for j in range(i + 1, num_dias):
            for k in range(num_actores):
                for l in range(num_actores):
                    vecino = asignacion.copy()
                    vecino[i, k], vecino[j, l] = vecino[j, l], vecino[i, k]
                    vecinos.append(vecino)
    return vecinos

# Búsqueda local heurística
def busqueda_local_heuristica(matriz_tomas, num_dias, num_actores, num_tomas_por_dia, max_iter):
    mejor_solucion = generar_solucion_inicial(num_dias, num_actores, num_tomas_por_dia)  # Genera una solución inicial aleatoria
    mejor_gasto = gasto_total(mejor_solucion, matriz_tomas)

    iteracion = 0
    mejora = True
    while mejora and iteracion < max_iter:  # Mientras haya mejora y no se alcance el máximo número de iteraciones
        mejora = False
        iteracion += 1
        for vecino in vecindad(mejor_solucion):
            gasto_vecino = gasto_total(vecino, matriz_tomas)
            if gasto_vecino < mejor_gasto:
                mejor_solucion = vecino
                mejor_gasto = gasto_vecino
                mejora = True

    return mejor_solucion, mejor_gasto

# Parámetros del problema
MAX_ITER = 1000
NUM_DIAS = 5
NUM_ACTORES = 10
NUM_TOMAS_POR_DIA = 6

# Ejecutar la búsqueda local heurística
mejor_solucion, gasto_mejor_solucion = busqueda_local_heuristica(matriz_tomas, NUM_DIAS, NUM_ACTORES, NUM_TOMAS_POR_DIA, MAX_ITER)

# Imprimir la mejor solución encontrada y su gasto total
print("La mejor solución encontrada es:")
print(mejor_solucion)
print("Coste total de la mejor solución:", gasto_mejor_solucion)


La mejor solución encontrada es:
[[4 1 2 4 4 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [6 5 6 5 5 6 7 5 8 0]
 [2 9 7 3 0 3 0 0 0 0]
 [8 0 4 8 8 9 0 0 0 0]]
Coste total de la mejor solución: 25


Esta solución representa la asignación de cada toma de la película a cada uno de los actores durante varios días de grabación.

Cada fila de la matriz representa un día de grabación, y cada columna representa un actor. El valor en cada celda indica la toma asignada al actor en ese día. Por ejemplo, el valor 4 en la primera fila y columna indica que la toma 4 fue asignada al actor 1 en el día 1.

