<a href="https://colab.research.google.com/github/JuanArocaMIAR/03MIAR---Algoritmos-de-Optimizacion---2023/blob/main/Trabajo_Pr%C3%A1ctico_Algoritmos_Juan_Aroca_Perez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Trabajo Práctico<br>
Nombre y Apellidos: Juan Aroca Perez <br>
Url: https://github.com/JuanArocaMIAR/03MIAR---Algoritmos-de-Optimizacion---2023.git<br>
Google Colab: https://colab.research.google.com/drive/xxxxxxxxxxxxxxxx <br>
Problema:
>1. Sesiones de doblaje <br>


**Descripción del problema:**

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible







                                        

#Modelo
- ¿Como represento el espacio de soluciones?
- ¿Cual es la función objetivo?
- ¿Como implemento las restricciones?

### **Problema 1:** Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graben. No es posible grabar más de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los servicios de los actores de doblaje sea el menor posible.

 La idea para resolver este programa es el empleo del problema tipo visto en la asignatura de **Programación lineal entera** puesto que, para empezar, todas las variables son de tipo entero. Además, cumple con la premisa de que hay que buscar un máximo o mínimo de una función objetivo lineal sujeto a restricciones, que en este caso, dichas restricciones serán que los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben y no es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible.

El objetivo del problema será **minimizar el gasto** total de los actores de doblaje. Por otro lado, como algoritmo de búsqueda de la solución, **vamos a emplear ramificación y poda**, para ello, necesitamos una estructura de árbol. Los actores y las tomas ya están colocados en la tabla.

 Las primeras **preguntas** que debemos hacernos son: ¿Cómo diseñamos el árbol? ¿Qué mecanismo diseñamos para ramificar? ¿Cómo podamos?.

 Una posible manera de **diseñar el árbol** es mediante una lista de tuplas, donde cada tupla representa una asignación parcial. Cada elemento de la tupla corresponde a un actor, y el valor en ese elemento indica a qué toma ha sido asignado ese actor como se vio en teoría. En el código que proporcionaste, una tupla del árbol de soluciones tiene la forma (a1, a2, ..., an), donde a_i es el número de toma a la cual el actor i ha sido asignado.

In [ ]:
# Estructura del árbol (lista de tuplas):
arbol = [(0, 0, 0, 0, 0, 0, 0, 0, 0, 0)]

# Función para generar hijos de un nodo:
def generar_hijos(nodo):
    hijos = []
    actores_no_asignados = [i for i in range(10) if nodo[i] == 0]
    for actor in actores_no_asignados:
        for toma in range(1, 11):
            hijo = list(nodo)
            hijo[actor] = toma
            hijos.append(tuple(hijo))
    return hijos

# Ramificación:
nodo_actual = arbol[0]
hijos = generar_hijos(nodo_actual)
print(hijos)

[(1, 0, 0, 0, 0, 0, 0, 0, 0, 0), (2, 0, 0, 0, 0, 0, 0, 0, 0, 0), (3, 0, 0, 0, 0, 0, 0, 0, 0, 0), (4, 0, 0, 0, 0, 0, 0, 0, 0, 0), (5, 0, 0, 0, 0, 0, 0, 0, 0, 0), (6, 0, 0, 0, 0, 0, 0, 0, 0, 0), (7, 0, 0, 0, 0, 0, 0, 0, 0, 0), (8, 0, 0, 0, 0, 0, 0, 0, 0, 0), (9, 0, 0, 0, 0, 0, 0, 0, 0, 0), (10, 0, 0, 0, 0, 0, 0, 0, 0, 0), (0, 1, 0, 0, 0, 0, 0, 0, 0, 0), (0, 2, 0, 0, 0, 0, 0, 0, 0, 0), (0, 3, 0, 0, 0, 0, 0, 0, 0, 0), (0, 4, 0, 0, 0, 0, 0, 0, 0, 0), (0, 5, 0, 0, 0, 0, 0, 0, 0, 0), (0, 6, 0, 0, 0, 0, 0, 0, 0, 0), (0, 7, 0, 0, 0, 0, 0, 0, 0, 0), (0, 8, 0, 0, 0, 0, 0, 0, 0, 0), (0, 9, 0, 0, 0, 0, 0, 0, 0, 0), (0, 10, 0, 0, 0, 0, 0, 0, 0, 0), (0, 0, 1, 0, 0, 0, 0, 0, 0, 0), (0, 0, 2, 0, 0, 0, 0, 0, 0, 0), (0, 0, 3, 0, 0, 0, 0, 0, 0, 0), (0, 0, 4, 0, 0, 0, 0, 0, 0, 0), (0, 0, 5, 0, 0, 0, 0, 0, 0, 0), (0, 0, 6, 0, 0, 0, 0, 0, 0, 0), (0, 0, 7, 0, 0, 0, 0, 0, 0, 0), (0, 0, 8, 0, 0, 0, 0, 0, 0, 0), (0, 0, 9, 0, 0, 0, 0, 0, 0, 0), (0, 0, 10, 0, 0, 0, 0, 0, 0, 0), (0, 0, 0, 1, 0, 0, 0, 0, 0, 0), (0, 

Tenemos una lista de tuplas que representa nuestra **espacio de soluciones**. Debido al volumen de datos, no es posible considerar una sola tupla como hemos visto en teoría, sería ineficiente. Las asignaciones parciales resultan más eficientes en este caso, donde cada nodo es una asignación parcial, lo que es aconsejable si vamos a realizar la técnica de ramificación y poda.

De este modo, por ejemplo, si tenemos la tupla (1, 3, 0, 2, 4, 5, 7, 6, 8, 9), significa que:

El actor 0 ha sido asignado a la toma 1.
El actor 1 ha sido asignado a la toma 3.
El actor 2 ha sido asignado a la toma 0.
El actor 3 ha sido asignado a la toma 2.
Y así sucesivamente.

**¿Cómo construimos la función objetivo?** Dado que **el objetivo es minimizar el gasto total** por los servicios de los actores de doblaje, necesitamos asignar un costo a cada toma asignada. **La matriz de costos** nos ayudará a determinar este costo para cada asignación de toma por actor.

In [ ]:
import random

# Tenemos 10 actores y 30 tomas.
num_actores = 10
num_tomas = 30

# Calculamos el número de tomas que cada actor debe realizar acorde a las restricciones.
tomas_por_dia = 6

# Creamos una matriz de costos con unos y ceros. 0 no realiza la toma, 1 realiza la toma.
matriz_costos = [[0] * num_actores for _ in range(num_tomas)]

# Hay que asignar seis unos en cada toma.
for j in range(num_tomas):
    actores_asignados = 0
    while actores_asignados < tomas_por_dia:
        i = random.randint(0, num_actores - 1)
        if matriz_costos[j][i] == 0:
            matriz_costos[j][i] = 1
            actores_asignados += 1

# Imprimimos por pantalla la matriz de costos:
print("Matriz de Costos:")
for fila in matriz_costos:
    print(fila)

Matriz de Costos:
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 1, 0, 1, 0, 1, 1, 0, 0]
[0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 1, 1, 0]
[1, 1, 1, 0, 0, 1, 0, 1, 1, 0]
[1, 0, 0, 1, 1, 0, 1, 1, 0, 1]
[1, 1, 0, 0, 1, 1, 0, 1, 0, 1]
[0, 0, 1, 0, 1, 1, 1, 1, 0, 1]
[1, 0, 1, 1, 0, 0, 1, 0, 1, 1]
[1, 1, 1, 1, 0, 0, 1, 0, 1, 0]
[1, 0, 0, 0, 0, 1, 1, 1, 1, 1]
[1, 0, 1, 0, 1, 1, 1, 0, 1, 0]
[1, 0, 0, 0, 1, 1, 0, 1, 1, 1]
[0, 1, 1, 1, 1, 1, 0, 0, 0, 1]
[0, 1, 1, 0, 0, 1, 1, 1, 0, 1]
[0, 1, 1, 1, 1, 0, 1, 1, 0, 0]
[1, 1, 0, 0, 0, 0, 1, 1, 1, 1]
[1, 0, 1, 1, 0, 1, 1, 0, 1, 0]
[0, 1, 0, 0, 1, 1, 0, 1, 1, 1]
[1, 1, 0, 0, 0, 0, 1, 1, 1, 1]
[1, 1, 1, 0, 1, 1, 0, 0, 0, 1]
[0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
[0, 0, 1, 1, 0, 0, 1, 1, 1, 1]
[0, 1, 1, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 1, 0, 0, 1, 1, 1, 0]
[1, 1, 0, 0, 1, 1, 0, 1, 1, 0]
[1, 0, 1, 0, 1, 1, 0, 1, 1, 0]
[0, 0, 1, 0, 1, 1, 1, 1, 1, 0]
[1, 0, 1, 0, 0, 1, 0, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]


 Vamos a proveernos de una función para estimar la **cota inferior para una solución parcial**. Tenemos que hacer una estimación, esto es la que nos va a servir para podar. Se trata de una estrategia para conducir al algoritmo a que sea más eficiente, o, a que dirija la búsqueda para encontrar la solución óptima. Para la cota inferior lo que **buscamos es el mínimo de esas columnas** para que nos sirva como función de cota inferior.

In [ ]:
import numpy as np

# Nuestro conjunto de datos original:
COSTES = np.array([
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
], dtype=int)

# Solución parcial: (1, 3, 0, 2, 4, 5, 7, 6, 8, 9) significa que el actor 0 ha sido asignado a la toma 1 y el actor 1 a la toma 3, al actor 3 la toma 0, y, así sucesivamente.
S_PARCIAL = np.array([1, 3, 0, 2, 4, 5, 7, 6, 8, 9])

def valor(S, COSTES):
    VALOR = 0
    for i in range(len(S)):
        VALOR += COSTES[S[i]][i]
    return VALOR

def CI(S, COSTES):
    VALOR = 0
    for i in range(len(S)):
        VALOR += COSTES[i][S[i]]

    for i in range(len(S), COSTES.shape[1]):
        VALOR += np.min(COSTES[:, i])

    return VALOR

print("Valor de la solución parcial:", valor(S_PARCIAL, COSTES))
print("Costo inferior:", CI(S_PARCIAL, COSTES))

Valor de la solución parcial: 2
Costo inferior: 2


#Análisis
- ¿Que complejidad tiene el problema?. Orden de complejidad y Contabilizar el espacio de soluciones

Dado que tenemos 10 actores y 30 tomas, tenemos un espacio de soluciones de 30**10 ya que cada actor puede ser asignado a cualquiera de las 30 tomas. El valor del espacio de soluciones es muy grande por lo que destaca la complejidad de explorar todo el espacio de soluciones y la necesidad de algoritmos como ramificación y poda para encontrar soluciones óptimas de manera eficiente.

El número total de soluciones tiene una expresión factorial. Esto se debe a que cada actor tiene 30 tomas entre las cuales puede ser asignado, y hay 10 actores en total, lo que supone un orden de complejidad O(N!), por lo que la técnica de ramificación y poda puede ser muy útil para reducir el número de búsqueda de soluciones.

#Diseño
- ¿Que técnica utilizo? ¿Por qué?

Lo siguiente será aplicar la **técnica de ramificación y poda**. Hemos definido el conjunto de datos que representa el problema de asignación de los actores por tomas. Hemos definido una matriz de costo asociado a cada actor por cada toma.

A continuación vamos a definir las funciones auxiliares: valor, CI, crear_hijos y ramificación_y_poda. Donde la función **valor** calcula el valor de una solución parcial, **CI** calcula una cota inferior para la solución parcial, **crear_hijos** genera los hijos de un nodo para la asignación de actores por tomas, y, la función principal **ramificación_y_poda** ejecuta el algoritmo ramificación y poda.

En la ramificación y poda se van a generar nodos y ramificar el árbol de búsqueda a través de un bucle. En cada iteración se seleccionará el nodo más prometedor basándose de la cota inferior. Se generarán los jijos mediante la función "crear_hijos". Como es necesario también realizar una poda, se eliminarán los nodos cuya cota inferior es mayor o igual a la mejor solución encontrada hasta el momento.

In [5]:
#Respuesta
import numpy as np
COSTES = np.array([
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
], dtype=int)

In [9]:
def valor(S, COSTES):
    VALOR = 0
    for i in range(len(S)):
        VALOR += COSTES[S[i]][i]
    return VALOR

In [11]:
def cota_inferior(S, COSTES):
    VALOR = 0
    for i in range(len(S)):
        VALOR += COSTES[i][S[i]]

    for i in range(len(S), COSTES.shape[1]):
        VALOR += np.min(COSTES[:, i])

    return VALOR

In [14]:
def crear_hijos(NODO, COSTES):
    HIJOS = []
    for i in range(len(COSTES)):
        if i not in NODO:
            HIJOS.append({'s': tuple(list(NODO) + [i])})
    return HIJOS

# Ejemplo de uso
nodo_actual = (0, 1, 3)
nuevos_hijos = crear_hijos(nodo_actual, COSTES)
print(nuevos_hijos)

[{'s': (0, 1, 3, 2)}, {'s': (0, 1, 3, 4)}, {'s': (0, 1, 3, 5)}, {'s': (0, 1, 3, 6)}, {'s': (0, 1, 3, 7)}, {'s': (0, 1, 3, 8)}, {'s': (0, 1, 3, 9)}, {'s': (0, 1, 3, 10)}, {'s': (0, 1, 3, 11)}, {'s': (0, 1, 3, 12)}, {'s': (0, 1, 3, 13)}, {'s': (0, 1, 3, 14)}, {'s': (0, 1, 3, 15)}, {'s': (0, 1, 3, 16)}, {'s': (0, 1, 3, 17)}, {'s': (0, 1, 3, 18)}, {'s': (0, 1, 3, 19)}, {'s': (0, 1, 3, 20)}, {'s': (0, 1, 3, 21)}, {'s': (0, 1, 3, 22)}, {'s': (0, 1, 3, 23)}, {'s': (0, 1, 3, 24)}, {'s': (0, 1, 3, 25)}, {'s': (0, 1, 3, 26)}, {'s': (0, 1, 3, 27)}, {'s': (0, 1, 3, 28)}, {'s': (0, 1, 3, 29)}]


Ahora lo siguiente sería: **Inicializamos la solución inicialmente con todo vacío**, y, nos vamos a ir guardando una **variable que llamamos NODOS**, los nodos que debemos explorar, los nodos vivos, con lo cual lo que hemos hecho es inicializar la solución.

In [7]:
#  Creamos el algoritmo de ramificación y poda para asignación de actores a tomas:
def ramificacion_y_poda(COSTES):
    DIMENSION = len(COSTES[0])
    MEJOR_SOLUCION = tuple(i for i in range(DIMENSION))
    CotaSup = valor(MEJOR_SOLUCION, COSTES)

    NODOS = []
    NODOS.append({'s': (), 'ci': CI((), COSTES)})

    iteracion = 0

Realizamos un **bucle iterativo**, lo que hacemos es ramificar, exploramos, **buscamos el nodo prometedor**. Hemos creado una **variable HIJOS** que va a guardar los hijos, porque lo que vamos a hacer posteriormente, es podarlos. **A continuación solamente añadiremos a NODOS a aquellos nodos que hayan pasado el filtro de la poda**.

In [16]:
import numpy as np

def calcular_valor(solucion, costos):
    valor_total = 0
    for i in range(len(solucion)):
        valor_total += costos[solucion[i]][i]
    return valor_total

def calcular_cota_inferior(solucion, costos):
    valor_total = 0
    for i in range(len(solucion)):
        valor_total += costos[i][solucion[i]]

    for i in range(len(solucion), costos.shape[1]):
        valor_total += np.min(costos[:, i])

    return valor_total

def generar_hijos(nodo, costos):
    hijos = []
    for i in range(len(costos)):
        if i not in nodo:
            hijos.append({'solucion': tuple(list(nodo) + [i])})
    return hijos

def ramificacion_y_poda(costos_actores):
    dimension = len(costos_actores[0])
    mejor_solucion = tuple(i for i in range(dimension))
    cota_superior = calcular_valor(mejor_solucion, costos_actores)

    nodos = []
    nodos.append({'solucion': (), 'cota_inferior': calcular_cota_inferior((), costos_actores)})

    iteracion = 0

    while len(nodos) > 0:
        iteracion += 1

        nodo_prometedor = min(nodos, key=lambda x: x['cota_inferior'])['solucion']

        # Generar hijos
        hijos = [{'solucion': x['solucion'], 'cota_inferior': calcular_cota_inferior(x['solucion'], costos_actores)} for x in generar_hijos(nodo_prometedor, costos_actores)]

        # Revisar la cota superior y actualizar la mejor solución si se encuentra una solución final
        nodo_final = [x for x in hijos if len(x['solucion']) == dimension]
        if len(nodo_final) > 0:
            if nodo_final[0]['cota_inferior'] < cota_superior:
                cota_superior = nodo_final[0]['cota_inferior']
                mejor_solucion = nodo_final[0]['solucion']

        # Poda
        hijos = [x for x in hijos if x['cota_inferior'] < cota_superior]

        # Añadir los hijos
        nodos.extend(hijos)

        # Eliminar el nodo ramificado
        nodos = [x for x in nodos if x['solucion'] != nodo_prometedor]

    print("La solución final es:", mejor_solucion, "en", iteracion, "iteraciones", "para dimension:", dimension)

# Usamos una matriz de costos de ejemplo para actores.
costos_actores_ejemplo = np.array([
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
], dtype=int)

ramificacion_y_poda(costos_actores_ejemplo)

IndexError: index 10 is out of bounds for axis 0 with size 10

In [40]:
import pandas as pd
import numpy as np
from google.colab import files

# Subir el archivo CSV desde tu sistema local
uploaded = files.upload()

# Seleccionar el archivo
datos = list(uploaded.keys())[0]

# Cargar el dataframe desde el archivo CSV
df_actores = pd.read_excel(datos, index_col=0)
print(df_actores)

Saving Datos problema doblaje(30 tomas, 10 actores).xlsx to Datos problema doblaje(30 tomas, 10 actores) (6).xlsx
       Actor  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  \
Toma     1.0         2.0         3.0         4.0         5.0         6.0   
1        1.0         1.0         1.0         1.0         1.0         0.0   
2        0.0         0.0         1.0         1.0         1.0         0.0   
3        0.0         1.0         0.0         0.0         1.0         0.0   
4        1.0         1.0         0.0         0.0         0.0         0.0   
5        0.0         1.0         0.0         1.0         0.0         0.0   
6        1.0         1.0         0.0         1.0         1.0         0.0   
7        1.0         1.0         0.0         1.0         1.0         0.0   
8        1.0         1.0         0.0         0.0         0.0         1.0   
9        1.0         1.0         0.0         1.0         0.0         0.0   
10       1.0         1.0         0.0         0.0  

In [41]:
df_actores = df_actores.drop(df_actores.index[0])
df_actores = df_actores.dropna(axis=0, how='all')
df_actores = df_actores.dropna(axis=1, how='all')

print(df_actores)


       Actor  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  \
1        1.0         1.0         1.0         1.0         1.0         0.0   
2        0.0         0.0         1.0         1.0         1.0         0.0   
3        0.0         1.0         0.0         0.0         1.0         0.0   
4        1.0         1.0         0.0         0.0         0.0         0.0   
5        0.0         1.0         0.0         1.0         0.0         0.0   
6        1.0         1.0         0.0         1.0         1.0         0.0   
7        1.0         1.0         0.0         1.0         1.0         0.0   
8        1.0         1.0         0.0         0.0         0.0         1.0   
9        1.0         1.0         0.0         1.0         0.0         0.0   
10       1.0         1.0         0.0         0.0         0.0         1.0   
11       1.0         1.0         1.0         0.0         1.0         0.0   
12       1.0         1.0         1.0         1.0         0.0         1.0   
13       1.0

In [44]:
columnas_actuales = df_actores.columns

nuevos_nombres = ['Actor {}'.format(i) for i in range(1, len(columnas_actuales))] + ['Total']

df_actores.columns = nuevos_nombres

df_actores.head()

Index(['Actor', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 12'],
      dtype='object')


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
1      1.0      1.0      1.0      1.0      1.0      0.0      0.0      0.0   
2      0.0      0.0      1.0      1.0      1.0      0.0      0.0      0.0   
3      0.0      1.0      0.0      0.0      1.0      0.0      1.0      0.0   
4      1.0      1.0      0.0      0.0      0.0      0.0      1.0      1.0   
5      0.0      1.0      0.0      1.0      0.0      0.0      0.0      1.0   

   Actor 9  Actor 10 Total  
1      0.0       0.0     5  
2      0.0       0.0     3  
3      0.0       0.0     3  
4      0.0       0.0     4  
5      0.0       0.0     3

In [45]:
display(df_actores)

Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
1          1.0      1.0      1.0      1.0      1.0      0.0      0.0      0.0   
2          0.0      0.0      1.0      1.0      1.0      0.0      0.0      0.0   
3          0.0      1.0      0.0      0.0      1.0      0.0      1.0      0.0   
4          1.0      1.0      0.0      0.0      0.0      0.0      1.0      1.0   
5          0.0      1.0      0.0      1.0      0.0      0.0      0.0      1.0   
6          1.0      1.0      0.0      1.0      1.0      0.0      0.0      0.0   
7          1.0      1.0      0.0      1.0      1.0      0.0      0.0      0.0   
8          1.0      1.0      0.0      0.0      0.0      1.0      0.0      0.0   
9          1.0      1.0      0.0      1.0      0.0      0.0      0.0      0.0   
10         1.0      1.0      0.0      0.0      0.0      1.0      0.0      0.0   
11         1.0      1.0      1.0      0.0      1.0      0.0      0.0      1.0   
12         1.0      1.0      1.0      1.0      0.0      1.0      0.0      0.0   
13         1.0      0.0      0.0      1.0      1.0      0.0      0.0      0.0   
14         1.0      0.0      1.0      0.0      0.0      1.0      0.0      0.0   
15         1.0      1.0      0.0      0.0      0.0      0.0      1.0      0.0   
16         0.0      0.0      0.0      1.0      0.0      0.0      0.0      0.0   
17         1.0      0.0      1.0      0.0      0.0      0.0      0.0      0.0   
18         0.0      0.0      1.0      0.0      0.0      1.0      0.0      0.0   
19         1.0      0.0      1.0      0.0      0.0      0.0      0.0      0.0   
20         1.0      0.0      1.0      1.0      1.0      0.0      0.0      0.0   
21         0.0      0.0      0.0      0.0      0.0      1.0      0.0      1.0   
22         1.0      1.0      1.0      1.0      0.0      0.0      0.0      0.0   
23         1.0      0.0      1.0      0.0      0.0      0.0      0.0      0.0   
24         0.0      0.0      1.0      0.0      0.0      1.0      0.0      0.0   
25         1.0      1.0      0.0      1.0      0.0      0.0      0.0      0.0   
26         1.0      0.0      1.0      0.0      1.0      0.0      0.0      0.0   
27         0.0      0.0      0.0      1.0      1.0      0.0      0.0      0.0   
28         1.0      0.0      0.0      1.0      0.0      0.0      0.0      0.0   
29         1.0      0.0      0.0      0.0      1.0      1.0      0.0      0.0   
30         1.0      0.0      0.0      1.0      0.0      0.0      0.0      0.0   
TOTAL     22.0     14.0     13.0     15.0     11.0      8.0      3.0      4.0   

       Actor 9  Actor 10 Total  
1          0.0       0.0     5  
2          0.0       0.0     3  
3          0.0       0.0     3  
4          0.0       0.0     4  
5          0.0       0.0     3  
6          0.0       0.0     4  
7          0.0       0.0     4  
8          0.0       0.0     3  
9          0.0       0.0     3  
10         1.0       0.0     4  
11         0.0       0.0     5  
12         0.0       0.0     5  
13         0.0       0.0     3  
14         0.0       0.0     3  
15         0.0       0.0     3  
16         0.0       1.0     2  
17         0.0       0.0     2  
18         0.0       0.0     2  
19         0.0       0.0     2  
20         0.0       0.0     4  
21         0.0       0.0     2  
22         0.0       0.0     4  
23         0.0       0.0     2  
24         0.0       0.0     2  
25         0.0       1.0     4  
26         1.0       0.0     4  
27         0.0       0.0     2  
28         0.0       0.0     2  
29         0.0       0.0     3  
30         0.0       0.0     2  
TOTAL      2.0       2.0   NaN

In [53]:
matriz_actores = df_actores.iloc[0:30, 0:10].astype(int).values
print(matriz_actores)

[[1 1 1 1 1 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0]
 [0 1 0 0 1 0 1 0 0 0]
 [1 1 0 0 0 0 1 1 0 0]
 [0 1 0 1 0 0 0 1 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 1 0]
 [1 1 1 0 1 0 0 1 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0]
 [1 0 1 0 0 1 0 0 0 0]
 [1 1 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 1]
 [1 0 1 0 1 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]]
